- name: Demo
  hosts: localhost
  remote_user: devops
  tasks:
  - name: Clone a repo with separate git directory
    ansible.builtin.git:
     repo: https://github.com/anandpavithran/DO180V4-14
     dest: /tmp/DO180V4-14
  - name: Copy1
    ansible.builtin.copy:
     src: /tmp/DO180V4-14/gluft
     dest: /usr/bin/gluft
     owner: root
     group: root
     mode: 0777
   
  - name: Copy2
    ansible.builtin.copy:
     src: /tmp/DO180V4-14/comset
     dest: /usr/lib/
  - name: Copy3
    ansible.builtin.copy:
     src: /tmp/DO180V4-14/vhelp
     dest: /usr/bin/vhelp
     owner: root
     group: root
     mode: 0777

  
